server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

jwt:
  token:
    header: api_key
    issuer: sto-back
    clientSecret: ${JWT_CLIENT_SECRET:}
    expirySeconds: 0

aws:
  access-key: ${AWS_ACCESS_KEY:}
  secret-key: ${AWS_SECRET_KEY:}

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      username: ${DB_USER:maca}
      password: ${DB_PASSWORD:}
      driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/cama}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true

    show-sql: false
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

iamport:
  key: ${IAMPORT_KEY:}
  secure: ${IAMPORT_SECRET:}
---

spring:
  config:
    activate:
      on-profile: prd
  datasource:
    hikari:
      username: ${DB_USER:maca}
      password: ${DB_PASSWORD:}
      driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://127.0.0.1:5432/cama}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true

    show-sql: false
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

iamport:
  key: ${IAMPORT_KEY:}
  secure: ${IAMPORT_SECRET:}
---

mybatis:
  config-location: classpath:mybatis-config.xml

cama:
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL:}
    webhook:
      dev: ${SLACK_WEBHOOK_DEV_URL:}
      prd: ${SLACK_WEBHOOK_PRD_URL:}

naver:
  oauth:
    client-id: ${NAVER_CLIENT_ID:}
    client-secret: ${NAVER_CLIENT_SECRET:}

apple:
  auth-key-path: ${APPLE_AUTH_KEY_PATH:}
